### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ph-moura** [ph-moura/IFGW-LaTeX#1]
- [x] Implement "cover".
- [x] Overfull \vbox.
- [x] Create an option to change the logo alignment.
- [x] Implement two languages title and other stuff.
- [x] Update coverpage.
- [x] Put a \newpage in the end of the \maketitle deffinition.
- [x] Create an "Epigraph command".
- [x] #4
- [x]  Underfull \hbox.
- [x] Include or not the foot in the total size of "bottom" (only if page number is in the foot).
- [x] Chapter in toc with \scshape
- [x] Redefine \theinstitute, \theuniversity, etc to two arguments.
- [x] Define a List of symbols and abreviations with hyperlink that goes back and forth.
